version: '3'
services:
  core_api:
    build: .
    container_name: core-api-container
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    volumes:
      - .:/app  # Mount the current directory inside the container
