name: CI/CD Pipeline for FastAPI

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch.
  pull_request:
    branches:
      - main  # Trigger on pull requests to the 'main' branch.

jobs:
  # Build job: Build and test the FastAPI application
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for the job
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx for building multi-architecture images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Cache Docker layers to speed up subsequent builds
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Step 4: Set up Python environment and install dependencies
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-car-recommender:${{ github.sha }} .

      # Step 6: Log in to Google Cloud using the service account credentials
      - name: Login to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      # Step 7: Push Docker image to Google Container Registry (GCR)
      - name: Push Docker image to Google Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-car-recommender:${{ github.sha }}

  # Deploy job: Deploy to Google Cloud Run
  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the 'build' job
    steps:
      # Step 1: Set up Google Cloud SDK (gcloud) to deploy to Cloud Run
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: '379.0.0'

      # Step 2: Deploy the Docker image to Google Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-car-recommender \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-car-recommender:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

