name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Ensure you're using Windows-based runner
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  # This sets PYTHONPATH to the root directory

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install httpx  # Ensure httpx is installed if not in requirements.txt

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Run tests with maxfail=1 and disable warnings
