name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # You can change this to 'windows-latest' if you're using Windows
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  # Set PYTHONPATH to the root directory of the repo

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install httpx  # Explicitly install httpx if it's not in the requirements.txt

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Run tests with maxfail=1 and disable warnings
