name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Install pytest here

      - name: Run tests
        run: |
          pytest  # Run pytest here

      - name: Build Docker image
        run: |
          docker build -t gcr.io/fastapi-442213/fastapi-car-recommender:latest .

      - name: Push Docker image
        run: |
          docker push gcr.io/fastapi-442213/fastapi-car-recommender:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-car-recommender \
            --image gcr.io/fastapi-442213/fastapi-car-recommender:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
